# Generated by Django 5.2.1 on 2025-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_remove_customer_address_customer_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('PH', 'Philippines'), ('US', 'United States')], default='PH', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_country_code',
            field=models.CharField(choices=[('+63', 'Philippines (+63)'), ('+1', 'United States (+1)')], default='+63', max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
