# Generated by Django 5.2.1 on 2025-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_customer_country_customer_mobile_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_country_code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
