# Generated by Django 5.2.1 on 2025-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_alter_customer_mobile_alter_customer_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveIntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.PositiveIntegerField(default=0, max_length=6),
        ),
    ]
