# Generated by Django 5.2.1 on 2025-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_alter_customer_mobile_alter_customer_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the order', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the status was last changed', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the order was last updated'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the order was created'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, help_text='Date when order was placed', null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending - Awaiting Payment'), ('Processing', 'Processing - Payment Confirmed'), ('Order Confirmed', 'Order Confirmed - In Production'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', help_text='Current status of the order', max_length=50, null=True),
        ),
    ]
