# Generated by Django 5.2.1 on 2025-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_orders_estimated_delivery_date_orders_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('paypal', 'PayPal')], default='cod', help_text='Payment method for the order', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending - Awaiting Payment'), ('Processing', 'Processing - Payment Confirmed'), ('Order Confirmed', 'Order Confirmed - In Production'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the order', max_length=50, null=True),
        ),
    ]
