# Generated by Django 5.2.1 on 2025-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('XS', 'Extra Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_ref',
            field=models.CharField(blank=True, help_text='Unique short order reference ID', max_length=12, null=True, unique=True),
        ),
    ]
