# Generated by Django 5.2.1 on 2025-06-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_customer_region_alter_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
    ]
