# Generated by Django 5.1.6 on 2025-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0030_remove_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='citymun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('R1', 'Ilocos Region'), ('R2', 'Cagayan Valley'), ('R3', 'Central Luzon'), ('R4A', 'CALABARZON'), ('R4B', 'MIMAROPA'), ('R5', 'Bicol Region'), ('R6', 'Western Visayas'), ('R7', 'Central Visayas'), ('R8', 'Eastern Visayas'), ('R9', 'Zamboanga Peninsula'), ('R10', 'Northern Mindanao'), ('R11', 'Davao Region'), ('R12', 'SOCCSKSARGEN'), ('R13', 'Caraga'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=100),
        ),
    ]
