# Generated by Django 5.2.1 on 2025-07-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0032_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='barangay',
            field=models.CharField(help_text="Barangay name, e.g. 'Barangay 1'", max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_municipality',
            field=models.CharField(help_text="City/Municipality name, e.g. 'Laoag City'", max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text="Province name, e.g. 'Ilocos Norte'", max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(help_text="Region name, e.g. 'Ilocos Region'", max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
