# Generated by Django 5.2.1 on 2025-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0033_alter_address_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(help_text="Enter 10 digits, e.g. '956 837 0169'", max_length=15),
        ),
    ]
