# Generated by Django 5.1.6 on 2025-07-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0036_alter_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=50)),
                ('origin_region', models.CharField(max_length=50)),
                ('destination_region', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_php', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
