# Generated by Django 5.2.4 on 2025-07-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0039_alter_customer_region_alter_savedaddress_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('01', 'REGION I (ILOCOS REGION)'), ('02', 'REGION II (CAGAYAN VALLEY)'), ('03', 'REGION III (CENTRAL LUZON)'), ('04', 'REGION IV-A (CALABARZON)'), ('17', 'REGION IV-B (MIMAROPA)'), ('05', 'REGION V (BICOL REGION)'), ('06', 'REGION VI (WESTERN VISAYAS)'), ('07', 'REGION VII (CENTRAL VISAYAS)'), ('08', 'REGION VIII (EASTERN VISAYAS)'), ('09', 'REGION IX (ZAMBOANGA PENINSULA)'), ('10', 'REGION X (NORTHERN MINDANAO)'), ('11', 'REGION XI (DAVAO REGION)'), ('12', 'REGION XII (SOCCSKSARGEN)'), ('13', 'NATIONAL CAPITAL REGION (NCR)'), ('14', 'CORDILLERA ADMINISTRATIVE REGION (CAR)'), ('15', 'AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)'), ('16', 'REGION XIII (Caraga)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product_image/default.svg', null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='region',
            field=models.CharField(choices=[('01', 'REGION I (ILOCOS REGION)'), ('02', 'REGION II (CAGAYAN VALLEY)'), ('03', 'REGION III (CENTRAL LUZON)'), ('04', 'REGION IV-A (CALABARZON)'), ('17', 'REGION IV-B (MIMAROPA)'), ('05', 'REGION V (BICOL REGION)'), ('06', 'REGION VI (WESTERN VISAYAS)'), ('07', 'REGION VII (CENTRAL VISAYAS)'), ('08', 'REGION VIII (EASTERN VISAYAS)'), ('09', 'REGION IX (ZAMBOANGA PENINSULA)'), ('10', 'REGION X (NORTHERN MINDANAO)'), ('11', 'REGION XI (DAVAO REGION)'), ('12', 'REGION XII (SOCCSKSARGEN)'), ('13', 'NATIONAL CAPITAL REGION (NCR)'), ('14', 'CORDILLERA ADMINISTRATIVE REGION (CAR)'), ('15', 'AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)'), ('16', 'REGION XIII (Caraga)')], max_length=2),
        ),
    ]
