# Generated by Django 5.2.4 on 2025-07-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0040_alter_customer_region_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text="Region name, e.g. 'Ilocos Region'", max_length=100)),
                ('province', models.CharField(help_text="Province name, e.g. 'Ilocos Norte'", max_length=100)),
                ('city_municipality', models.CharField(help_text="City/Municipality name, e.g. 'Laoag City'", max_length=100)),
                ('barangay', models.CharField(help_text="Barangay name, e.g. 'Barangay 1'", max_length=100)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='savedaddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='savedaddress',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('R1', 'Ilocos Region'), ('R2', 'Cagayan Valley'), ('R3', 'Central Luzon'), ('R4A', 'CALABARZON'), ('R4B', 'MIMAROPA'), ('R5', 'Bicol Region'), ('R6', 'Western Visayas'), ('R7', 'Central Visayas'), ('R8', 'Eastern Visayas'), ('R9', 'Zamboanga Peninsula'), ('R10', 'Northern Mindanao'), ('R11', 'Davao Region'), ('R12', 'SOCCSKSARGEN'), ('R13', 'Caraga'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('R1', 'Ilocos Region'), ('R2', 'Cagayan Valley'), ('R3', 'Central Luzon'), ('R4A', 'CALABARZON'), ('R4B', 'MIMAROPA'), ('R5', 'Bicol Region'), ('R6', 'Western Visayas'), ('R7', 'Central Visayas'), ('R8', 'Eastern Visayas'), ('R9', 'Zamboanga Peninsula'), ('R10', 'Northern Mindanao'), ('R11', 'Davao Region'), ('R12', 'SOCCSKSARGEN'), ('R13', 'Caraga'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=100),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='street_address',
            field=models.CharField(max_length=100),
        ),
    ]
