# Generated by Django 4.2.7 on 2025-09-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0044_cartitem_created_at_cartitem_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='size',
        ),
    ]
