# Generated by Django 4.2.7 on 2025-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0045_remove_orders_product_remove_orders_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for this order', max_digits=10),
        ),
    ]
