# Generated by Django 4.2.7 on 2025-09-09 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0046_orders_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='admin_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='handover_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='handover_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='handover_status',
            field=models.CharField(choices=[('bot', 'Bot Handling'), ('requested', 'Admin Help Requested'), ('admin', 'Admin Handling'), ('resolved', 'Resolved')], default='bot', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('admin', 'Admin Response'), ('system', 'System Message')], max_length=10),
        ),
    ]
